import "dotenv/config";
import { z } from "zod";

const envSchema = z.object({
  PORT: z.string().default("4000"),
  DATABASE_URL: z.string().min(1),
  SECURITY_MODE: z.enum(["dev", "staging", "production"]).default("dev"),
  ALLOWED_ORIGIN: z.string().default("https://khan-automation-systems-frontend.vercel.app"),
  ALLOWED_ORIGINS: z.string().optional(),
  ALLOWED_ORIGIN_REGEX: z.string().optional(),
  JWT_SECRET: z.string().min(16),
  REFRESH_TOKEN_SECRET: z.string().optional(),
  ACCESS_TOKEN_TTL_MINUTES: z.string().default("15"),
  REFRESH_TOKEN_TTL_DAYS: z.string().default("14"),
  PASSWORD_RESET_TTL_MINUTES: z.string().default("30"),
  JWT_EXPIRES_IN: z.string().default("7d"),
  SMTP_HOST: z.string().optional(),
  SMTP_PORT: z.string().default("587"),
  SMTP_SECURE: z.string().default("false"),
  SMTP_USER: z.string().optional(),
  SMTP_PASS: z.string().optional(),
  SMTP_FROM: z.string().default("Khan Automation Systems <no-reply@example.com>"),
  RESEND_API_KEY: z.string().optional(),
  RESEND_FROM: z.string().optional(),
  LEAD_NOTIFICATION_EMAIL: z.string().email(),
  ADMIN_EMAIL: z.string().email(),
  ADMIN_PASSWORD: z.string().min(8),
  ADMIN_ACTION_PASSWORD: z.string().min(8),
  STRIPE_SECRET_KEY: z.string().default("sk_test_placeholder"),
  STRIPE_WEBHOOK_SECRET: z.string().default("whsec_placeholder"),
  STRIPE_STARTER_PRICE_ID: z.string().default("price_starter_placeholder"),
  STRIPE_PRO_PRICE_ID: z.string().default("price_pro_placeholder"),
  STRIPE_PRO_SEAT_PRICE_ID: z.string().optional(),
  STRIPE_FOUNDING_PRICE_ID: z.string().optional(),
  STRIPE_STARTER_SETUP_FEE_PRICE_ID: z.string().optional(),
  STRIPE_PRO_SETUP_FEE_PRICE_ID: z.string().optional(),
  STRIPE_FOUNDING_SETUP_FEE_PRICE_ID: z.string().optional(),
  STRIPE_SUCCESS_URL: z.string().default("https://khan-automation-systems-frontend.vercel.app/checkout/success"),
  STRIPE_CANCEL_URL: z.string().default("https://khan-automation-systems-frontend.vercel.app/checkout/cancel"),
  STRIPE_PORTAL_RETURN_URL: z.string().optional(),
  FRONTEND_APP_URL: z.string().default("https://khan-automation-systems-frontend.vercel.app"),
  API_BASE_URL: z.string().default("https://ai-auto-apply.onrender.com"),
  AUTO_LIVE_ON_SETUP: z.string().default("false"),
  TWILIO_ACCOUNT_SID: z.string().optional(),
  TWILIO_AUTH_TOKEN: z.string().optional(),
  TWILIO_PHONE_SID: z.string().optional(),
  VAPI_API_KEY: z.string().optional(),
  VAPI_PRIVATE_KEY: z.string().optional(),
  VAPI_TOOL_SECRET: z.string().optional(),
  DEMO_VAPI_TOOL_SECRET: z.string().optional(),
  WEBHOOK_STRICT_MODE: z.string().default("true"),
  LOG_REDACTION_ENABLED: z.string().default("true"),
  ENCRYPTION_KEY_BASE64: z.string().optional(),
  GOOGLE_OAUTH_CLIENT_ID: z.string().optional(),
  GOOGLE_OAUTH_CLIENT_SECRET: z.string().optional(),
  GOOGLE_OAUTH_CALLBACK_URL: z.string().optional(),
  OUTLOOK_OAUTH_CLIENT_ID: z.string().optional(),
  OUTLOOK_OAUTH_CLIENT_SECRET: z.string().optional(),
  OUTLOOK_OAUTH_CALLBACK_URL: z.string().optional(),
  OPENAI_API_KEY: z.string().optional(),
  ADMIN_2FA_REQUIRED_IN_PROD: z.string().default("true"),
  AUTH_2FA_ENFORCE_ALL_USERS: z.string().default("false"),
  AUTH_2FA_TRUST_DAYS: z.string().default("1"),
  VAPI_BACKFILL_ENABLED: z.string().default("true"),
  VAPI_BACKFILL_INTERVAL_MS: z.string().default("60000"),
  ROUTING_ENGINE_ENABLED: z.string().default("false"),
  AUTO_RECOVERY_ENABLED: z.string().default("false"),
  SLA_MONITOR_ENABLED: z.string().default("false"),
  DATA_INTEGRITY_GUARD_ENABLED: z.string().default("true"),
  AUTO_RECOVERY_DEDUPE_WINDOW_HOURS: z.string().default("2"),
  AUTO_RECOVERY_DAILY_CAP: z.string().default("50"),
  CALL_QUALITY_MIN_SCORE: z.string().default("75"),
  SLA_MONITOR_INTERVAL_MS: z.string().default("60000"),
  DATA_INTEGRITY_GUARD_INTERVAL_MS: z.string().default("3600000"),
  SLA_WARN_WEBHOOK_FAILURES: z.string().default("5"),
  SLA_CRITICAL_WEBHOOK_FAILURES: z.string().default("10"),
  SLA_WARN_PROVIDER_ERRORS: z.string().default("5"),
  SLA_CRITICAL_PROVIDER_ERRORS: z.string().default("10"),
  SLA_CRITICAL_CONSECUTIVE_BREACHES: z.string().default("2"),
  SLA_RECOVERY_WINDOWS_REQUIRED: z.string().default("2"),
  OPS_ORG_EXPOSURE_THRESHOLD: z.string().default("0.5"),
  OPS_TRAFFIC_EXPOSURE_THRESHOLD: z.string().default("0.5"),
  GUIDED_DEMO_ENABLED: z.string().default("true"),
  GUIDED_DEMO_WINDOW_DAYS: z.string().default("7"),
  GUIDED_DEMO_TOTAL_CALL_CAP: z.string().default("15"),
  GUIDED_DEMO_UPGRADE_SMS_COOLDOWN_HOURS: z.string().default("24"),
  GUIDED_DEMO_UPGRADE_SMS_TEMPLATE: z.string().default(
    "Thanks for calling {{businessName}}. Your guided demo call limit has been reached. Reply here or upgrade in your billing portal to continue AI call handling."
  ),
  FEATURE_APPOINTMENTS_ENABLED: z.string().default("false"),
  FEATURE_CALENDAR_OAUTH_ENABLED: z.string().default("false"),
  FEATURE_NOTIFICATIONS_V1_ENABLED: z.string().default("false"),
  FEATURE_CLASSIFICATION_V1_ENABLED: z.string().default("false"),
  FEATURE_PIPELINE_STAGE_ENABLED: z.string().default("false"),
  FEATURE_PHASE1_ORG_ALLOWLIST: z.string().default(""),
  WEBHOOK_RATE_LIMIT_WINDOW_MS: z.string().default("60000"),
  WEBHOOK_RATE_LIMIT_MAX: z.string().default("600"),
  TOOL_RATE_LIMIT_WINDOW_MS: z.string().default("60000"),
  TOOL_RATE_LIMIT_MAX: z.string().default("300")
});

const parsed = envSchema.safeParse(process.env);
if (!parsed.success) {
  // eslint-disable-next-line no-console
  console.error(parsed.error.flatten().fieldErrors);
  throw new Error("Invalid environment configuration.");
}

export const env = {
  ...parsed.data,
  // Accept either name so existing deployments using VAPI_PRIVATE_KEY keep working.
  VAPI_API_KEY: parsed.data.VAPI_API_KEY || parsed.data.VAPI_PRIVATE_KEY
};
